services:
- type: web
  name: AstroPeliculasOfSearchBot
  env: node
  plan: starter
  buildCommand: npm install
  startCommand: npm start
  envVars:
  - key: TELEGRAM_TOKEN
    value: 6501994235:AAGR2S96c-hgHV1Cj8fDHej70VTGqimFUO4
  - key: TMDB_KEY
    value: 74dc824830c7f93dc61b03e324070886
  port: 8225